### ISSUE TITLE
cost

### ISSUE THREAD

**Issue by riyadhuddin** [aws-samples/healthlake-workshop#6]
I am writing my problem here as I didn't see any other contact available about this workshop.
I  have followed the workshop URL from this repo and The overall cost for the workshop was **supposed to be <$15.**
I didn't do an extra but only **step 1 to 3 which is**, 
Step 1: Setup, Import and Export
Step 2: Data Transformation using Glue
Step 3: Table Preparation using Athena 
It took me approximately two hours to do so and I had something else to do So I did follow the cleanup instructions. The next morning **I've got $309.33 bills from HealthLake only!** 
![awsbill](https://user-images.githubusercontent.com/13874736/143416508-4f8d5b2b-125e-43a7-a7c7-6ee029889f75.JPG)
Please help me understand what's gone wrong, was it my fault or? 
**I remember deleting HealthLake datastore, s3 and SageMaker instances were removed with CloudFormation  Stack.**
Region: us-east-1
Thank You.

**Comment by awsbakha** [comment]
We are updating workshop sample code and instructions to lower the cost and also reflect true cost of running the workshop.
